---

all:
  children:
    databases:
      children:
        # PostgreSQL and PGPool-II are in same host
        mixed_pool:
          children:
            postgresqls:
              hosts:
                10.233.89.3:
                10.233.89.5:
            pgpools:
              hosts:
                10.233.89.3:
                10.233.89.5:
        # PostgreSQL and PGPool-II are in different hosts
        distributed_pool:
          children:
            postgresqls:
              hosts:
                10.233.89.11:
                10.233.89.19:
            pgpools:
              hosts:
                10.233.89.43:
                10.233.89.47:
