---

all:
  children:
    databases:
      children:
        postgresqls:
          hosts:
            10.233.89.11:
            10.233.89.19:
        pgpools:
          hosts:
            10.233.89.43:
            10.233.89.47:
